apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-deployment
  labels:
    app: home
spec:
  replicas: 1
  selector:
    matchLabels:
      app: home
  template:
    metadata:
      labels:
        app: home
    spec:
      containers:
      - name: home
        image: 654654261302.dkr.ecr.us-east-1.amazonaws.com/shopping-site-home:44084c4ddd0d75a673164f0149bcf67a22c3bdc7
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: home-service
  labels:
    app: home
spec:
  type: ClusterIP
  selector:
    app: home
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
