apiVersion: apps/v1
kind: Deployment
metadata:
  name: auto-deployment
  labels:
    app: auto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auto
  template:
    metadata:
      labels:
        app: auto
    spec:
      containers:
      - name: auto
        image: 673405670859.dkr.ecr.us-east-1.amazonaws.com/shopping-site-auto:a3c05d93c9a390a5e7408455c070e96f31c7e368
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: auto-service
  labels:
    app: auto
spec:
  type: ClusterIP
  selector:
    app: auto
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
